name: nicotine
version: git
summary: test
adopt-info: nicotine
license: GPL-3.0+

base: core22
confinement: strict

apps:
  nicotine:
    command: usr/bin/nicotine
    common-id: org.nicotine_plus.Nicotine
    desktop: usr/share/applications/org.nicotine_plus.Nicotine.desktop
    extensions: [gnome]
    plugs:
      - home
      - network

parts:
  nicotine:
    plugin: python
    source: .
    source-type: git
    parse-info: [usr/share/metainfo/org.nicotine_plus.Nicotine.appdata.xml]

slots:
  nicotine:
    interface: dbus
    bus: session
    name: org.nicotine_plus.Nicotine
