title: Nicotine+
logo: /files/icons/scalable/nicotine-plus.svg
description: A graphical client for the SoulSeek peer-to-peer system a

plugins:
  - jekyll-relative-links

relative_links:
  enabled: true
  collections: true

exclude:
  - files/README
  - files/win32/upnpc/upnpc-static.exe
  - img/README
  - plugins/README

theme: jekyll-theme-minimal
