plugins:
  - jekyll-relative-links
relative_links:
  enabled: true
  collections: true
include:
  - README.md
  - AUTHORS.md
exclude:
  - pynicotine
  - sounds
  - test
  - tools

theme: jekyll-theme-minimal
