plugins:
  - jekyll-relative-links
relative_links:
  enabled: true
  collections: true
include:
  - README.md
  - AUTHORS.md
exclude:
  - .github
  - debian
  - doc
  - files
  - img
  - languages
  - manpages
  - plugins
  - pynicotine
  - sounds
  - test
  - tools

theme: jekyll-theme-minimal
