plugins:
  - jekyll-relative-links
relative_links:
  enabled: true
  collections: true
include:
  - README.md
  - AUTHORS.md
exclude:
  - files/README
  - img/README
  - plugins/README

theme: jekyll-theme-minimal
