name: Continuous Integration (DEP-8)

on: [push, pull_request]

jobs:

  ubuntu:
    runs-on: ${{ matrix.os }}
    strategy:
      matrix:
        os: [ubuntu-18.04, ubuntu-20.04]
    env:
      NICOTINE_SOURCE_DIRECTORY: ${{ github.action_path }}
    steps:
      - name: Checkout code
        uses: actions/checkout@v2
        with:
          fetch-depth: 0

      - name: Install autopkgtest dependencies
        run: |
          sudo apt update
          sudo apt -y install autopkgtest

      - name: Run autopkgtest
        run: |
          cd packaging/
          sudo autopkgtest . -- null
