name: Packaging (Debian, Windows and macOS)

on: [push, pull_request]

jobs:

  debian:
    runs-on: ubuntu-20.04
    steps:
      - name: Checkout code
        uses: actions/checkout@v2
        with:
          fetch-depth: 0

      - name: Set up Python
        uses: actions/setup-python@v2
        with:
          python-version: 3.9

      - name: Install dependencies
        run: |
          sudo sed -Ei 's/^# deb-src /deb-src /' /etc/apt/sources.list
          sudo apt update
          sudo apt build-dep .

      - name: Build Debian package
        run: |
          # Generate tarball
          python setup.py sdist
          mk-origtargz dist/nicotine-plus-*.tar.gz

          # Build source package
          debuild -S -sa -us -uc

          # Build binary
          debuild -b -sa -us -uc

      - name: Prepare artifacts
        run: |
          mkdir ../build/
          cp -Lr ../nicotine_* ../build/

      - name: Archive artifacts
        uses: actions/upload-artifact@v1
        with:
          name: debian-package
          path: ../build/

  flatpak:
    runs-on: ubuntu-20.04
    container:
      image: bilelmoussaoui/flatpak-github-actions:gnome-3.38
      options: --privileged
    steps:
    - uses: actions/checkout@v2
    - uses: bilelmoussaoui/flatpak-github-actions@v2
      with:
        bundle: flatpak-package.flatpak
        manifest-path: packaging/flatpak/org.nicotine_plus.Nicotine.yaml
        run-tests: true

  windows:
    runs-on: windows-latest
    strategy:
      matrix:
        include: [
          { msystem: MINGW64, arch: x86_64 },
          { msystem: MINGW32, arch: i686   }
        ]
    defaults:
      run:
        shell: msys2 {0}
    steps:
      - name: Checkout code
        uses: actions/checkout@v2
        with:
          fetch-depth: 0

      - name: Setup msys2
        uses: msys2/setup-msys2@v2
        with:
          msystem: ${{ matrix.msystem }}
          update: true

      - name: Install build dependencies
        run: |
          export ARCH=${{ matrix.arch }}
          packaging/windows/dependencies-core.sh
          packaging/windows/dependencies-packaging.sh

      - name: Build installer
        run: |
          export ARCH=${{ matrix.arch }}
          pyinstaller packaging/windows/nicotine.spec
          makensis -DARCH=${{ matrix.arch }} packaging/windows/nicotine.nsi
          mkdir installer
          cp -r packaging/windows/Nicotine*.exe installer/

      - name: Archive installer artifacts
        uses: actions/upload-artifact@v2
        with:
          name: windows-${{ matrix.arch }}-installer
          path: installer

      - name: Archive package artifacts
        uses: actions/upload-artifact@v2
        with:
          name: windows-${{ matrix.arch }}-package
          path: dist

  macos:
    runs-on: macos-10.15
    steps:
      - name: Checkout code
        uses: actions/checkout@v2
        with:
          fetch-depth: 0

      - name: Install build dependencies
        run: |
          packaging/macos/dependencies-core.sh
          packaging/macos/dependencies-packaging.sh

      - name: Freeze application
        run: |
          pyinstaller packaging/macos/nicotine.spec
          rm -rf dist/Nicotine+/

      - name: Ad-hoc signing
        run: |
          codesign --deep --entitlements packaging/macos/entitlements.plist --options runtime --sign - dist/Nicotine+.app

      - name: Generate .dmg
        run: |
          packaging/macos/create-dmg.sh

      - name: Archive installer artifacts
        uses: actions/upload-artifact@v2
        with:
          name: macos-installer
          path: dmg
