name: Packaging (Windows and macOS)

on: [push, pull_request]

jobs:

  windows:
    runs-on: windows-latest
    strategy:
      matrix:
        include: [
          { msystem: MINGW64, arch: x86_64 },
          { msystem: MINGW32, arch: i686   }
        ]
    defaults:
      run:
        shell: msys2 {0}
    steps:
      - name: Checkout code
        uses: actions/checkout@v2
        with:
          fetch-depth: 0

      - name: Setup msys2
        uses: msys2/setup-msys2@v2
        with:
          msystem: ${{ matrix.msystem }}
          update: true

      - name: Install build dependencies
        run: |
          export ARCH=${{ matrix.arch }}
          files/windows/dependencies-core.sh
          files/windows/dependencies-packaging.sh

      - name: Build installer
        run: |
          export ARCH=${{ matrix.arch }}
          pyinstaller files/windows/nicotine.spec
          makensis -DARCH=${{ matrix.arch }} files/windows/nicotine.nsi
          mkdir installer
          cp -r files/windows/Nicotine*.exe installer/

      - name: Archive installer artifacts
        uses: actions/upload-artifact@v1
        with:
          name: windows-${{ matrix.arch }}-installer
          path: installer

      - name: Archive package artifacts
        uses: actions/upload-artifact@v1
        with:
          name: windows-${{ matrix.arch }}-package
          path: dist

  macos:
    runs-on: macos-latest
    steps:
      - name: Checkout code
        uses: actions/checkout@v2
        with:
          fetch-depth: 0

      - name: Install build dependencies
        run: |
          files/macos/dependencies-core.sh
          files/macos/dependencies-packaging.sh

      - name: Freeze application
        run: |
          pyinstaller files/macos/nicotine.spec
          rm -rf dist/Nicotine+/

      - name: Generate .dmg
        run: |
          files/macos/create-dmg.sh
          codesign -s - dmg/Nicotine+.dmg

      - name: Archive installer artifacts
        uses: actions/upload-artifact@v1
        with:
          name: macos-installer
          path: dmg
