name: In-Tree Unit Tests

on: [push, pull_request]

jobs:

  ubuntu:
    runs-on: ubuntu-latest
    strategy:
      matrix:
        python: [3.5, 3.6, 3.7, 3.8, 3.9, 3.10.0-beta.1, pypy-3.6, pypy-3.7]
    steps:
      - name: Checkout code
        uses: actions/checkout@v2
        with:
          fetch-depth: 0

      - name: Set up Python ${{ matrix.python }}
        uses: actions/setup-python@v2
        with:
          python-version: ${{ matrix.python }}

      - name: Install dependencies
        run: |
          sudo apt update
          sudo apt install gir1.2-gtk-3.0 libgirepository1.0-dev
          python -m pip install flake8 pep8-naming pygobject pytest

      - name: Lint with flake8
        run: |
          python -m flake8

      - name: Unit tests
        run: |
          xvfb-run python -m pytest

  windows:
    runs-on: windows-latest
    defaults:
      run:
        shell: msys2 {0}
    steps:
      - name: Checkout code
        uses: actions/checkout@v2
        with:
          fetch-depth: 0

      - name: Setup msys2
        uses: msys2/setup-msys2@v2
        with:
          msystem: MINGW64
          update: true

      - name: Install dependencies
        run: |
          export ARCH=x86_64
          packaging/windows/dependencies-core.sh

      - name: Lint with flake8
        run: |
          flake8

      - name: Unit tests
        run: |
          pytest

  macos:
    runs-on: macos-latest
    steps:
      - name: Checkout code
        uses: actions/checkout@v2
        with:
          fetch-depth: 0

      - name: Install dependencies
        run: |
          packaging/macos/dependencies-core.sh

      - name: Lint with flake8
        run: |
          flake8

      - name: Unit tests
        run: |
          pytest
